### ISSUE TITLE
should add a return after the report

### ISSUE THREAD

**Issue by zzzgit** [jodonnell/jest-simple-dot-reporter#1]
![image](https://user-images.githubusercontent.com/1060733/56450670-3e017480-635a-11e9-875e-1d5e77a78998.png)

You should add a `\r\n` here, don't be messy with coverage report.

**Comment by Userbit** [comment]
This issue has fixed in PR #2

**Comment by jodonnell** [comment]
i never got a notification for this, sorry for the long delay, pr #2  has been merged in

**Comment by jodonnell** [comment]
and a release was created 1.0.5
